server:
  port: 8084

spring:
  profiles: dev
  application:
    name: abcmsc-provider-depart
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    type: alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///testdb2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 1234

  eureka:
    client:
      service-url:
        #defaultZone: http://localhost:8100/eureka,http://localhost:8200/eureka,http://localhost:8300/eureka
        defaultZone: http://localhost:8400/eureka

---

server:
  port: 8085

spring:
  profiles: test
  application:
    name: abcmsc-provider-depart
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    type: alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///testdb2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 1234

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8100/eureka,http://localhost:8200/eureka,http://localhost:8300/eureka
      defaultZone: http://localhost:8500/eureka